const fs = require("fs");
const path = require("path");

const projectDir = __dirname;
const outputFile = path.join(projectDir, "quizzes.js");

function getQuestionCount(quiz) {
    if (!Array.isArray(quiz?.questions)) {
        return 0;
    }

    return quiz.questions.reduce((total, group) => {
        const groupQuestions = Array.isArray(group?.questions) ? group.questions.length : 0;
        return total + groupQuestions;
    }, 0);
}

function getQuizOrder(fileName, quiz) {
    const titleMatch = String(quiz?.title || "").match(/Quiz\s+(\d+)/i);

    if (titleMatch) {
        return Number.parseInt(titleMatch[1], 10);
    }

    const fileMatch = fileName.match(/quiz(\d+)/i);
    return fileMatch ? Number.parseInt(fileMatch[1], 10) : Number.MAX_SAFE_INTEGER;
}

function buildCombinedQuiz(quizzes) {
    return {
        title: "Osszes quiz",
        description: `${quizzes.length} quiz egyben`,
        questions: quizzes.flatMap((quiz) => {
            return Array.isArray(quiz?.questions) ? quiz.questions : [];
        })
    };
}

function loadQuizFiles() {
    const quizFiles = fs.readdirSync(projectDir)
        .filter((fileName) => /^quiz.*\.json$/i.test(fileName))
        .sort((left, right) => left.localeCompare(right, "en"));

    const loadedQuizzes = quizFiles.map((fileName) => {
        const filePath = path.join(projectDir, fileName);
        const raw = fs.readFileSync(filePath, "utf8");
        const quiz = JSON.parse(raw);

        return { fileName, quiz };
    });

    loadedQuizzes.sort((left, right) => {
        const orderDifference = getQuizOrder(left.fileName, left.quiz) - getQuizOrder(right.fileName, right.quiz);

        if (orderDifference !== 0) {
            return orderDifference;
        }

        return String(left.quiz?.title || "").localeCompare(String(right.quiz?.title || ""), "hu");
    });

    return loadedQuizzes.map(({ quiz }) => quiz);
}

function buildOutput(quizzes) {
    const allQuizzes = [buildCombinedQuiz(quizzes), ...quizzes];
    const serializedQuizzes = JSON.stringify(allQuizzes, null, 4);

    return `// Generated by generate-quizzes.js. Do not edit manually.\nwindow.quizzes = ${serializedQuizzes};\n\nwindow.getQuestionCount = function getQuestionCount(quiz) {\n    if (!Array.isArray(quiz?.questions)) {\n        return 0;\n    }\n\n    return quiz.questions.reduce((total, group) => {\n        const groupQuestions = Array.isArray(group?.questions) ? group.questions.length : 0;\n        return total + groupQuestions;\n    }, 0);\n};\n`;
}

function main() {
    const quizzes = loadQuizFiles();

    if (quizzes.length === 0) {
        throw new Error("Nem talaltam quiz JSON fajlokat.");
    }

    fs.writeFileSync(outputFile, buildOutput(quizzes));

    const totalQuestions = quizzes.reduce((total, quiz) => total + getQuestionCount(quiz), 0);
    console.log(`Generated quizzes.js with ${quizzes.length} quizzes and ${totalQuestions} questions.`);
}

main();
